pollster/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

pollster/polls/urls.py
from django.urls import path
from . import views

# Criação das rotas de nosso site. O arquivo 'urls' que está na pasta principal 'pollster', está criando as rotas padrões do site (tipo o 'app.use()' do JS):

app_name = 'polls'
urlpatterns = [
    # Se deixarmos como '', ele usará a rota configurada no 'urls.py' da pasta principal 'pollster'.
    path('', views.index, name='index'),
    # Estamos definindo que um parâmetro deverá ser passado nesta rota, no caso um inteiro chamado 'question_id'.
    path('<int:question_id>/', views.details, name='details'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

pollster/pollster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('pages.urls')),
]

pollster/pages/models.py
from django.db import models

# Create your models here.

pollster/polls/models.py
'''
- Módulo responsável pela criação dos modelos que serão usados no site, segundo o padrão MVC.

OBS: O Django já cria uma primary key automaticamente para cada modelo em nossa base de dados, que por padrão é o sqlite3.

OBS 2: Logo após criarmos os modelos, devemos rodar:
1) 'python manage.py makemigrations polls' - Que cria o arquivo contendo o código responsável pela criação das tabelas na base de dados;
2) 'python manage.py migrate' - Que cria as respectivas tabelas dos modelos na base de dados, segundo o arquivo criado na primeira etapa.

OBS 3: Podemos relizar queries diretamente do terminal, rodando: 'python manage.py shell', sendo que podemos rodar, exemplo:
>>> from polls.models import Question, Choice
>>> from django.utils import timezone                                          
>>> q = Question(question_text='What is your favorite Python framework ?',pub_date=timezone.now()) 
>>> q.save()
>>> q.id
1
>>> q.question_text
'What is your favorite Python framework ?'
>>> Question.objects.all()
<QuerySet [<Question: What is your favorite Python framework ?>]>
>>> Question.objects.filter(id=1) 
<QuerySet [<Question: What is your favorite Python framework ?>]>
>>> Question.objects.get(pk=1) 
<Question: What is your favorite Python framework ?>
>>> q2 = Question.objects.get(pk=1) 
>>> q2.choice_set.all()
<QuerySet []>
>>> q2.choice_set.create(choice_text="Django",votes=0) 
<Choice: Django>
>>> q2.choice_set.create(choice_text="Flask",votes=0)  
<Choice: Flask>
>>> q2.choice_set.create(choice_text="Web2py",votes=0) 
<Choice: Web2py>
>>> q2.choise_set.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Question' object has no attribute 'choise_set'
>>> q2.choice_set.all() 
<QuerySet [<Choice: Django>, <Choice: Flask>, <Choice: Web2py>]>
'''

from django.db import models


class Question(models.Model):
    # Abaixo definimos os campos que teremos na classe Question, no caso o campo será de caracteres:
    question_text = models.CharField(max_length=200)
    # O texto será disponibilizado quando o campo for acionado:
    pub_date = models.DateTimeField('date published')

    # Quando formos nos referir a classe dentro no módulo 'admin', por padrão ele aparecerá como 'Question.object', sendo que queremos que apareça o conteúdo do texto, assim como nos 'Choices':
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    # Abaixo criamos uma relação entre os modelos, tabelas:
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollster/pages/views.py
from django.shortcuts import render

# Esta página será uma landing page, caso alguém acesse o site pela url basica, sem ser pelo polls.


def index(request):
    return render(request, 'pages/index.html')

pollster/polls/views.py
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Question, Choice

# Obtem as questões e as mostra nos templates criados:


def index(request):
    # Obtemos a lista das cinco questões de nosso modelo na base, ordenando-as pela data de publicação, de fora descendente:
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # Criamos um objeto tipo JSON com essa lista e passamos para renderizar no site.
    context = {'latest_question_list': latest_question_list}
    # Definimos em 'settings' o nosso diretório de templates, abaixo ele irá reconhecer e auto-preencher a url para o index.html.
    return render(request, 'polls/index.html', context)

# Mostra os detalhes específicos de um questão e das opções:


def details(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/details.html', {'question': question})

# Identifica a questão e mostra seus resultados:


def results(request, question_id):
    # Abaixo utilizamos um 'django shortcut', que nos permite procurar um item na base de dados e caso não encontre, retorna um erro 404. Desta forma não precisamos usar um try / catch, por exemplo.
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

# Registra o voto para aquela opção:


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        # OBS 1 - O Djando ORM (Object Relational Mapper) gera um método para os modelos que utilizam da foreign key, atráves do 'RelatedManager'. O 'foo_set', que neste caso é 'choice_set', é criado de forma que podemos acessar as opções, questões, diretamente pelo nosso modelo de perguntas.
        # OBS 2 - O request.POST['choice'] se refere ao form criado no template 'details.html', lá o form possui um id único como 'choiceX'(X sendo o número daquela iteração), deste, quando rodamos o POST, podemos acessar o atributo 'value' e incrementá-lo
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
            'question': question,
            'error message': 'Please select a choice.'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Sempre devemos retornar um HttpResponseRedirect depois de lidarmos com sucesso com um POST data. Desta forma previnimos que seja feito duas vezes, se o usuário clicar no botão de back.
        # O 'reverse' é um método para construção de URL, pois podemos receber demais argumentos dentro dele.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

pollster/templates/base.html
<!--Criamos este HTML base para ser usado pelos demais templates, onde usamos os placeholders 'entre chaves' abaixo.-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <title>Pollster {% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

pollster/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
    <div class="card-body">
        <h1>Welcome To Pollster</h1>
        <p>This is an example of Django polling app</p>
        <a href="{% url 'polls:index' %}" class="btn btn-dark">View Available Polls</a>
    </div>
</div>

{% endblock %}

pollster/templates/partials/_navbar.html
<!--Template parcial, usado apenas como um snippet para as demais aplicações usarem-->
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a href="/" class="navbar-brand">Pollster</a>
    </div>
</nav>

pollster/templates/polls/details.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url 'polls:index' %}" class="btn btn-secondary btn-sm mb-3">Back To Polls</a>
<h1 class="text-center mb-3">{{question.question_text}}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{error_message}}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST" class="d-grid">
    <!--O token 'csrf' serve como uma crossref, para garantir que a url não foi forjada-->
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <div class="form-check">
            <!--O 'forloop.counter' nos é uma outra feature do Django, que nos possibilita saber em qual a iteração estamos-->
            <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}" value="{{choice.id}}">
            <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label>
        </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg mt-4">
</form>

{% endblock %}

pollster/templates/polls/index.html
<!--Usamos a estratégia de separar todos os templates em uma pasta, seprada de nossos apps. Uma outra seria criar uma pasta templates para cada app, mas isso pode ficar confuso com o tempo-->

{% extends 'base.html' %}
{% block content %}

<h1 class="text-center mb-3">Poll Questions</h1>

<!--Checa se existem questões em nosso banco, essa lista foi gerada e disponibilizada na view do app polls-->
{% if latest_question_list %}
    {% for question in latest_question_list %}
        <div class="card mb-3">
            <div class="card-body">
                <p class="lead">{{ question.question_text }}</p>
                <!--Criamos um link com o app 'polls', onde iremos mostrar a view 'details' e 'results', com o id especifico da questão informada-->
                <a href="{% url 'polls:details' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
            </div>
        </div>
    {% endfor %}
{% else %}
    <p>No polls available</p>
{% endif %}

{% endblock %}

pollster/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}

<h1 class="mb-5 text-center">{{question.question_id}}</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
        <li class="list-group-item">
            {{choice.choice_text}} <span class="badge bg-success float-end">
                <!--No 'vote' usamos um 'helper' do Django, onde, se tiver apenas um voto, ele irá escrever no singular, caso tenha mais, no plural (pluralize)-->
                {{choice.votes}} vote{{choice.votes | pluralize}}
            </span>
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:index' %}" class="btn btn-secondary">Back To Polls</a>
<a href="{% url 'polls:details' question.id %}" class="btn btn-dark">Vote Again ?</a>

{% endblock %}